---
- name: Copy /etc/hosts to other server
  template:
    src: "hosts"
    dest: "{{ tmp_dir }}"
    mode: 644
    force: no
  become: yes

- name: Add /etc/hosts
  shell: cat /tmp/hosts >> /etc/hosts
  args:
    executable: /bin/bash