
---
- name: Copy script
  template:
    src: "script.sh"
    dest: "{{ tmp_dir }}"
    mode: 744
    force: no
  become: yes

- name: Run Script
  shell: sh /tmp/script.sh
  args:
    executable: /bin/bash